In [136]:
import pandas as pd
import numpy as np
abc = pd.read_html("https://stattrek.com/multiple-regression/regression-coefficients.aspx")
matr= abc[5] #select table
x =matr.drop('Test score',axis=1)#independent variable
y = matr['Test score'] #dependent variable
x['Student'] = 1
x_transpose = np.matrix(x).T
y_transpose = np.matrix(y).T
t = x_transpose*np.matrix(x) #multiply x trasnpose and x 
inverse = np.linalg.inv(t)
coef = inverse*x_transpose*y_transpose # this return coefficient(b0,b1,b2 ....)

In [139]:
matr

Student  Test score   IQ  Study hours
0        1         100  110           40
1        2          90  120           30
2        3          80  100           20
3        4          70   90            0
4        5          60   80           10

In [149]:
x

Student   IQ  Study hours
0        1  110           40
1        1  120           30
2        1  100           20
3        1   90            0
4        1   80           10

In [150]:
y

0    100
1     90
2     80
3     70
4     60
Name: Test score, dtype: int64

In [140]:
b0 = coef[0]
b1= coef[1]
b2 = coef[2]
print("İntercept: {} b1: {} b2: {}".format(b0,b1,b2))

İntercept: [[20.]] b1: [[0.5]] b2: [[0.5]]


In [141]:
equation = b0+b1*20+b2*50
print(equation)

[[55.]]


In [152]:
predict =[b0+b1*x1+b2*x2 for x1,x2 in zip(x['IQ'],x['Study hours'])]
predict

[matrix([[95.]]),
 matrix([[95.]]),
 matrix([[80.]]),
 matrix([[65.]]),
 matrix([[65.]])]

In [153]:
total = [(yi-y_pred)**2 for yi,y_pred in zip(y,predict)]
mse = float(np.array(sum(total)/n))
rmse = float(mse**(1/2))
print("MSE: {} and RMSE: {}".format(mse,rmse))

MSE: 20.0 and RMSE: 4.47213595499958


In [31]:
# from sklearn.linear_model import LinearRegression

In [145]:
ab = pd.read_html("https://stattrek.com/multiple-regression/regression-coefficients.aspx")
table = ab[5]
baglı = table["Test score"]
bagsız = table.drop(['Test score','Student'],axis=1)
model = LinearRegression().fit(bagsız,baglı)
model.intercept_
model.coef_

array([0.5, 0.5])

In [113]:
from sklearn.metrics import mean_squared_error

In [146]:
y_pred = model.predict(matr[['IQ','Study hours']])

In [147]:
np.sqrt(mean_squared_error(matr['Test score'],y_pred))

4.47213595499958